### ISSUE TITLE
Update Pi Image

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/raspi-deployment-microservice#89]
In addition to updating, we can install the packages that are installed by `pi-setup.sh` (including docker, if `apt update` updates it as well). By doing this, the time to setup a new pi will speed up a lot.

**Comment by dannyrandall** [comment]
If the possibility to update docker completely, without just reinstalling it, exists, we can add the pi user to the docker group as well.

**Comment by xuther** [comment]
we also need to make sure that ssh is enabled.

**Comment by xuther** [comment]
This has been addressed.
